import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} `}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function() {
        function getThemePreference() {
          if (typeof localStorage !== 'undefined' && localStorage.getItem('theme')) {
            return localStorage.getItem('theme');
          }
          // Default to dark mode instead of checking system preference
          return 'dark';
        }
        
        const theme = getThemePreference();
        document.documentElement.classList.toggle('dark', theme === 'dark');
      })();
     `,
          }}
        />

        {children}
      </body>
    </html>
  );
}
